# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-27 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20190427_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userask',
            old_name='phone',
            new_name='mobile',
        ),
    ]
